//----------------------------------------------------------------------------
// Herc Havoc -- Starsiege map buildings. GENERATED by tools/hh_ss_mission.py.
// Exec'd from modDataBlocks.cs (pre-preload).
//----------------------------------------------------------------------------
StaticShapeData HHShape_hmarsfusionreactor
{
   shapeFile = "hmarsfusionreactor";
   maxDamage = 999.0;
   description = "hmarsfusionreactor";
};

StaticShapeData HHShape_hmarswaterconverter
{
   shapeFile = "hmarswaterconverter";
   maxDamage = 999.0;
   description = "hmarswaterconverter";
};

StaticShapeData HHShape_hmarswatertower
{
   shapeFile = "hmarswatertower";
   maxDamage = 999.0;
   description = "hmarswatertower";
};

StaticShapeData HHShape_hmeethall
{
   shapeFile = "hmeethall";
   maxDamage = 999.0;
   description = "hmeethall";
};

StaticShapeData HHShape_hpolicefin
{
   shapeFile = "hpolicefin";
   maxDamage = 999.0;
   description = "hpolicefin";
};

StaticShapeData HHShape_hpolicehq
{
   shapeFile = "hpolicehq";
   maxDamage = 999.0;
   description = "hpolicehq";
};

StaticShapeData HHShape_hrefinery
{
   shapeFile = "hrefinery";
   maxDamage = 999.0;
   description = "hrefinery";
};

StaticShapeData HHShape_huplink
{
   shapeFile = "huplink";
   maxDamage = 999.0;
   description = "huplink";
};

StaticShapeData HHShape_xzendark
{
   shapeFile = "xzen_dark";
   maxDamage = 999.0;
   description = "xzen_dark";
};

