//------------------------------------------------------------------
// Starsiege asset pack -- generated by tools/ss_package.py
//
// Mounts the converted Starsiege corpus.  Nothing here is visible to
// Tribes until this mod is selected, so the whole pack is a one-line
// rollback.  Archives are plain zips (renamed from .vol to .zip at Joe's
// direction for the v18 ship; the engine mounts by zip magic).
//
// Starsiege_conflicts.zip is deliberately NOT mounted: every file in it
// shares a name with an asset Tribes already ships (or with a prepared
// herc from the Mech Mayhem port), and mounting it would shadow them.
// Starsiege_reference.zip holds Starsiege's own .cs/.gui/.dlg for
// porting reference; it is data, not scripts to run.
//------------------------------------------------------------------

function StarsiegeMountVolumes()
{
   newObject("SS_vol00", SimVolume, "Starsiege_01.zip");
   newObject("SS_vol01", SimVolume, "Starsiege_02.zip");
   newObject("SS_vol02", SimVolume, "Starsiege_03.zip");
   newObject("SS_vol03", SimVolume, "Starsiege_04.zip");
   newObject("SS_vol04", SimVolume, "Starsiege_05.zip");
   newObject("SS_vol05", SimVolume, "Starsiege_06.zip");
   newObject("SS_vol06", SimVolume, "Starsiege_sounds_01.zip");
   newObject("SS_vol07", SimVolume, "Starsiege_sounds_02.zip");
   newObject("SS_vol08", SimVolume, "Starsiege_interiors.zip");
   newObject("SS_vol09", SimVolume, "Starsiege_terrain.zip");
   newObject("SS_vol10", SimVolume, "Starsiege_fonts.zip");
   newObject("SS_vol11", SimVolume, "Starsiege_media_01.zip");
   newObject("SS_vol12", SimVolume, "Starsiege_media_02.zip");
   newObject("SS_vol13", SimVolume, "Starsiege_media_03.zip");
   newObject("SS_vol14", SimVolume, "Starsiege_media_04.zip");
   newObject("SS_vol15", SimVolume, "Starsiege_media_05.zip");
}

StarsiegeMountVolumes();
echo("Starsiege asset pack mounted");

// Boot-time proof that the ENGINE resolves assets out of the archives.
// The opt-out guard lives INSIDE the self-test and tests for the positive
// value: an unset console var reads as "" and coerces to 0, so `!= 0` on
// an unset pref is FALSE and would silently skip the check entirely.
exec("Starsiege_selftest.cs");
