    MissionList::clear();
    $TALT::Active = true;
//    MissionList::addMission("BastardForgeLT");
    MissionList::addMission("BroadsideLT");
    //MissionList::addMission("CanyonCrusadeLT");
	MissionList::addMission("CanyonCrusadeDeluxeLT");
//    MissionList::addMission("CloakOfDayLT");
    MissionList::addMission("DangerousCrossingLT");
//    MissionList::addMission("DesertOfDeathLT");
//    MissionList::addMission("EmeraldValleyLT");
//    MissionList::addMission("HildebrandLT");
    MissionList::addMission("HillKingLT");
    MissionList::addMission("HillSideLT");
//    MissionList::addMission("IceDaggerLT");
//    MissionList::addMission("IceRidgeLT");
//    MissionList::addMission("JaggedClawLT");
    MissionList::addMission("LotusLT");
//    MissionList::addMission("MiddayMayhemLT");
	MissionList::addMission("MiddayMayhemDeluxeLT");
//    MissionList::addMission("ObfuscationLT");
    MissionList::addMission("RaindanceLT");
//    MissionList::addMission("RaindanceDeluxeLT");
//    MissionList::addMission("ReliquaryLT");
//    MissionList::addMission("RhaskicLT");
    MissionList::addMission("RollercoasterLT");
//    MissionList::addMission("RunoutLT");
//    MissionList::addMission("RunwayLT");
//    MissionList::addMission("SimoomLT");
//    MissionList::addMission("SnowblindLT");
//    MissionList::addMission("SpinCycleLT");
//    MissionList::addMission("StarFallLT");
    MissionList::addMission("StonehengeLT");
    MissionList::addMission("SulfuriousLT");
//    MissionList::addMission("TesseractLT");
    
    $pref::LastMission = "HillSideLT";
    MissionList::initNextMission();